version: "3.8"

services:

  mysqlserver:
    image: mysql:8.0.23
    container_name: mysqlserver
    ports:
      - 3307:3306
      - 80:80
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=meli-frescos
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    networks:
      - sonarnet
    ports:
      - 8081:8080
    links:
      - sonarqube:sonarqube
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - /var/jenkins/caches:/var/jenkins/caches
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    #command:
    #-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true

  jmeter-master:
    image: vmarrazzo/jmeter
    container_name: jmeter
    volumes:
      - .:/mnt/jmeter
    command: -s -n -Jserver.rmi.ssl.disable=true
    ports:
    - 6000:6000

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    depends_on:
      - mysqlserver
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    #environment:
     # - sonar.jdbc.username=sonar
     # - sonar.jdbc.password=sonar
     # - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8082"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  mysql_data:
  mysql_config: