version: "3.8"

services:
  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3307:3306
      - 80:80
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=meli-frescos
      - DATADOG_HOST=datadog
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
  redis:
    image: redis
    command: redis-server --requirepass Redis!
    ports:
      - "6379:6379"
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
        - 8081:8080
    container_name: jenkins
    volumes:
        #- /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql_data:
  mysql_config: